"""add achievements

Revision ID: 98dfc1df423c
Revises: 88a8a6b0d0a3
Create Date: 2023-11-09 22:46:55.714593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98dfc1df423c'
down_revision: Union[str, None] = '88a8a6b0d0a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievements', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('achievements', 'image')
    # ### end Alembic commands ###
